version: "3.8"

services:
  stock-checker:
    build: .
    restart: unless-stopped
    environment:
      - TARGET_URL=${TARGET_URL}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
      - MIN_INTERVAL_IN_SECONDS=${MIN_INTERVAL_IN_SECONDS}
      - MAX_INTERVAL_IN_SECONDS=${MAX_INTERVAL_IN_SECONDS}
      - NODE_ENV=production
    security_opt:
      - no-new-privileges:true
    user: "1000:1000" # Ensure it's not running as root
    read_only: true # Prevents unnecessary write access
